title: "Hello, world! I'm Sung-Jaewoo."
description: >
  This is a blog for self-development and my portfolio.
baseurl: ""
url: "https://sung-jaewoo.github.io"
site-twitter:

# Author Settings
author: "Sung-Jaewoo"
author-img: "simple_profile_image.png"
about-author: "I am a university student focusing on back-end development. Always hungry to keep learning."
social-github: "Sung-Jaewoo"
social-email: "willsung0407@gmail.com"

# Disqus
discus-identifier: "mr-brown"

# Tracker
analytics:

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
